import os
from dataclasses import dataclass, field


@dataclass
class ElementBlock:
    element_type: str
    elements: dict[int, tuple[int, ...]]
    elset_name: str


@dataclass
class MeshData:
    nodes: dict[int, tuple[float, float, float]]
    element_blocks: list[ElementBlock]
    node_sets: dict[str, list[int]] = field(default_factory=dict)
    element_sets: dict[str, list[int]] = field(default_factory=dict)
    metadata: dict[str, object] = field(default_factory=dict)


def write_inp(path, data):
    parent = os.path.dirname(os.path.abspath(path))
    if parent and not os.path.isdir(parent):
        os.makedirs(parent)
    with open(path, "w", encoding="utf-8") as handle:
        _write_heading(handle, data.metadata)
        handle.write("*PART, NAME=MESH_CONVERT\n")
        handle.write("*NODE\n")
        for node_id in sorted(data.nodes):
            x, y, z = data.nodes[node_id]
            handle.write("{}, {:.12g}, {:.12g}, {:.12g}\n".format(node_id, x, y, z))
        for block in data.element_blocks:
            handle.write(
                "*ELEMENT, TYPE={}, ELSET={}\n".format(
                    block.element_type, _sanitize_name(block.elset_name)
                )
            )
            for element_id in sorted(block.elements):
                connectivity = ", ".join(str(node) for node in block.elements[element_id])
                handle.write("{}, {}\n".format(element_id, connectivity))
        for name, nodes in sorted(data.node_sets.items()):
            handle.write("*NSET, NSET={}\n".format(_sanitize_name(name)))
            _write_id_lines(handle, nodes)
        for name, elements in sorted(data.element_sets.items()):
            handle.write("*ELSET, ELSET={}\n".format(_sanitize_name(name)))
            _write_id_lines(handle, elements)
        handle.write("*END PART\n")


def _write_heading(handle, metadata):
    handle.write("*HEADING\n")
    handle.write("** Generated by mesh_convert\n")
    for key in sorted(metadata):
        handle.write("** {}: {}\n".format(key, metadata[key]))


def _write_id_lines(handle, ids):
    unique_ids = sorted(set(int(value) for value in ids))
    for index in range(0, len(unique_ids), 16):
        handle.write(", ".join(str(value) for value in unique_ids[index : index + 16]))
        handle.write("\n")


def _sanitize_name(name):
    text = str(name or "SET")
    sanitized = []
    for char in text:
        if char.isalnum() or char == "_":
            sanitized.append(char)
        else:
            sanitized.append("_")
    return "".join(sanitized)[:80] or "SET"
